import json

# 1. Simulated inputs from test file
prompts = [
    "What is the sum of 2 and 3?",
    "Reverse the string 'hello'",
    "Calculate the square root of 144"
]

# 2. Simulated minified raw JSON generated by the LLM (no newlines/extra spaces)
llm_outputs = [
    '{"name":"fn_add_numbers","parameters":{"a":2.0,"b":3.0}}',
    '{"name":"fn_reverse_string","parameters":{"s":"hello"}}',
    '{"name":"fn_get_square_root","parameters":{"a":144.0}}'
]

# 3. Process and combine them exactly as __main__.py will
final_results = []
for prompt_text, raw_json in zip(prompts, llm_outputs):
    parsed_llm = json.loads(raw_json)
    
    # Construct final dictionary matching expected schema
    item = {
        "prompt": prompt_text,
        "name": parsed_llm["name"],
        "parameters": parsed_llm["parameters"]
    }
    final_results.append(item)

# 4. Dump to file with indent=2
output_path = "test_output.json"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(final_results, f, indent=2)

# 5. Read back the exact text from the file and print it raw
print("=== FILE CONTENT START ===")
with open(output_path, "r", encoding="utf-8") as f:
    print(f.read())
print("=== FILE CONTENT END ===")